### ISSUE TITLE
Code to run application in background

### ISSUE THREAD

**Issue by Zoham** [DebarunaS/laughtercapture#1]
Please implement a code to run the python application main.py in the background.

**Comment by simpleParadox** [comment]
##### There is an application known as **AlwaysUp** which is used to start any kind of application and keep running it in the background as a windows service.

###### In your case, you want to run a python file. 
              So point the executable to the python.exe file from your program files, and point to the python file you want to start executing.

I am attaching a link below for a better and concise explanation.
[How to run any python script in Windows in the background](https://www.youtube.com/watch?v=aXu6T4XfZGU)

@Zoham 
#1
